RoyalPages/urls.py
from django.urls import path

from . import views

app_name = "RoyalPages"
urlpatterns = [
    path("", views.home, name="home"),
    path("posts/<int:pk>", views.blog_post, name="blog"),
    path("Posts", views.posts, name="posts"),
    path("About us", views.about, name="about"),
    path("Gallery", views.gallery, name="gallery"),
    path("search", views.search_results, name="search")
]

RoyalSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('RoyalPages.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RoyalPages/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
class AboutUs(models.Model):
    """The info about the enterprise to displayed"""
    title = models.CharField(max_length=200)
    order = models.IntegerField()
    text = models.TextField()
    background = CloudinaryField("RoyalArcSite/backgrounds", null=True, blank=True)
    def __str__(self):
        """Returns a string representation of the model"""
        return f"{self.title[:50]} ({self.order})"
        
class BlogPost(models.Model):
    """An entry in a bloggers web journal"""
    title = models.CharField(max_length=200)
    cover = CloudinaryField("RoyalArcSite/covers", default='media\backgrounds\defualt_images.png')
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    views = models.IntegerField(default=0, null=True, blank=True)

    def __str__(self):
        """Returns a string representation of the model"""
        return self.title[:50]

class Catergory(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return self.name

class Image(models.Model):
    """Pictures mooore pictures"""
    title = models.CharField(max_length=200, null=True, blank=True)
    image = CloudinaryField("RoyalArcSite/gallery")

RoyalPages/views.py
from django.shortcuts import render

import json
import os
import re
from math import floor, ceil

from django.http import JsonResponse
from django.core import serializers
from django.shortcuts import render

from .models import BlogPost, AboutUs, Image

def home(request):
    abouts = AboutUs.objects.all()
    abouts = filename(abouts)
    abouts_qs = prep_json(abouts)
    context = {'home':"home", 'abouts': abouts, 'abouts_qs': abouts_qs, 'name': 'Home'}
    return render(request, "RoyalPages/home.html", context)

def about(request):
    abouts = AboutUs.objects.all()
    abouts_qs = prep_json(abouts)
    context = {'abouts': abouts, 'abouts_qs': abouts_qs, 'name':'About Us'}
    return render(request, "RoyalPages/about.html", context)

def blog_post(request, pk):
    """Display the details of a blog post"""
    post = BlogPost.objects.get(pk=pk)
    post.views = post.views + 1
    post.save()
    context = {'post': post, 'name': post.title}
    return render(request, "RoyalPages/post.html", context)

def filename(query_set):
    for item in query_set:
        print(item.background)
        item.background = os.path.basename(str(item.background))
    return query_set

def prep_json(query_set):
    # case = re.compile(r'\s')
    # briefcase = []
    for item in query_set:
        item.text = item.text.replace('\r', '\\r')
        item.text = item.text.replace('\n', '\\n')
        item.text = item.text.replace("\'", "\\'")
        item.text = item.text.replace('\"', '\\"')
        item.text = item.text.replace('\t', '\\t')
        item.text = item.text.replace('\&', '\\&')
        item.text = item.text.replace('\f', '\\f')
        item.text = item.text.replace('\b', '\\b')
    query_set = serializers.serialize("json", query_set)
    return query_set

def prep_jsons(query_set):
    # briefcase = []
    dots = re.compile(r'\\.')
    for item in query_set:
        item.title = re.escape(item.title)
        item.title = item.title.replace('\ ', ' ')
        item.title = dots.sub('.', item.title)
        item.title = item.title.replace('.\\', '.')
        item.text = re.escape(item.text)
        item.text = item.text.replace('\ ', ' ')
        item.text =  dots.sub('.', item.text)
        item.text = item.text.replace('.\\', '.')

    query_set = serializers.serialize("json", query_set)
    return query_set

# def prep_json_popular(query_set):
#     briefcase = []
#     dots = re.compile(r'\\.')
#     for item in query_set:
#         item.title = re.escape(item.title)
#         item.title = item.title.replace('\ ', ' ')
#         item.title = dots.sub('.', item.title)
#         item.title = item.title.replace('.\\', '.')
#         item.text = re.escape(item.text)
#         item.text = item.text.replace('\ ', ' ')
#         item.text =  dots.sub('.', item.text)
#         item.text = item.text.replace('.\\', '.')
        
#         # print(type(item.cover))
#         item.cover = re.escape(str(item.cover))
#         item.cover = item.cover.replace('\ ', ' ')
#         item.cover =  dots.sub('.', item.cover)
#         item.cover = item.cover.replace('.\\', '.')

#     query_set = serializers.serialize("json", query_set)
    # return query_set

def extractor(array, num):
    for item in array:
        if len(item.text.split()) > 10 * num:
            item.title = item.title.title()
            item.text = item.text.split()
            item.text = item.text[:10 * num]
            item.text = ' '.join(item.text)
            item.text+='...'  
    return(array)

def p_extractor(array, num):
    array = list(array)
    for ar in range(len(array)):
        array[ar] = list(array[ar])
    for item in array:
        if len(item[1].split()) > 10 * num:
            item[0] = item[0]
            item[1] = item[1]
            item[1] = item[1].split()
            item[1] = item[1][:10*num]
            item[1] = ' '.join(item[1])
            item[1] += '...'
    return(array)

def diction(alist):
    print(alist)
    diction = {}
    for item in range(len(alist)):
        diction.setdefault(f'item', {'title': alist[item][0], 'text': alist[item][1], 'pk': alist[item][2]})
    print(type(diction))
    return diction

def posts(request):
    posts = BlogPost.objects.order_by('-date_added')
    popular = BlogPost.objects.order_by('-views')
    popular_qs = BlogPost.objects.order_by('-views').values_list('title', 'text', 'pk')
    popular_qs = p_extractor(popular_qs, 2)
    popular = extractor(popular, 2)
    posts = extractor(posts, 10)
    popular_qs = json.dumps(diction(popular_qs))
    # popular_qs = serializers.serialize('json', popular_qs)
    context = {'posts': posts, 'popular': popular, 'popular_qs': popular_qs, 'name':'Posts'}
    print(popular_qs)
    return render(request, "RoyalPages/posts.html", context)

def gallery(request):
    gallery = Image.objects.order_by('-id')
    gallery_qs = serializers.serialize("json", gallery)
    context = {'gallery': gallery, "gallery_qs": gallery_qs, 'name':'Gallery'}
    return render(request, "RoyalPages/gallery.html", context)

def search_results(request):
    if request.is_ajax():
        post = request.POST.get('post')
        qs = extractor(BlogPost.objects.filter(title__icontains=post), 2)
        if len(qs) > 0 and len(post) > 0:
            data = []
            for pos in qs:
                item = {
                    'pk': pos.pk,
                    'title': pos.title,
                    'text': pos.text,
                    # 'cover': str(pos.cover.url),
                    'date_added': pos.date_added,
                    'views': pos.views
                }
                data.append(item)
            res = data
        else:
            res = 'No matching posts found...'
        return JsonResponse({'data': res})
    return JsonResponse({})

def add_posts(request):
    pass

RoyalPages/templates/RoyalPages/about.html
{% extends 'RoyalPages/base.html' %}
{% load static %}

{% block intro %}
<section>
  <h1>About Us</h1>
</section>
{% endblock intro %}
{% block body %}
<!-- <img id="background" src="{% static 'RoyalSite/images/architecture.jpg' %}"> -->
<div class="content">
  <div id="left">
    <ul id="left-list">

    </ul>
  </div>
  <div id="right">
    <ul id="right-list">

    </ul>
  </div>
</div>
<script>
  const data = '{{abouts_qs}}'
  const rdata = JSON.parse(data.replace(/&quot;/g, '"'))
  length = Math.ceil(rdata.length/2)
  var i = 0;
  
  rdata.forEach((e, index) => {if (index < length) {
    const title = document.createElement('b')
    title.innerHTML = e.fields.title
    const text = document.createElement('p')
    text.innerHTML = e.fields.text
    document.getElementById('left-list').append(title)
    document.getElementById('left-list').append(text)
  }
  else {
    const title = document.createElement('b')
    title.innerHTML = e.fields.title
    const text = document.createElement('p')
    text.innerHTML = e.fields.text
    document.getElementById('right-list').append(title)
    document.getElementById('right-list').append(text)
  };
  })
  
</script>
{% endblock body %}

RoyalPages/templates/RoyalPages/base.html
{% load static %}

<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
    <meta content="utf-8" http-equiv="encoding">
    <title>Royal Arc Cleaning Services: {{name}}</title>
    <meta name="description" content="Managing a number of different properties can be a real balancing act. You want to offer the best experience possible to your client or building, avoid unexpected problems, and save money. Our clients have a reputation for quality service and well maintained buildings. Join the Royal family and experience royal treatment for yourself. Get in touch with us today for a free quote.">
    <meta property="og:title" content="Royal Arc Cleaning Services">
    <meta property="og:description" content="Managing a number of different properties can be a real balancing act. You want to offer the best experience possible to your client or building, avoid unexpected problems, and save money. Our clients have a reputation for quality service and well maintained buildings. Join the Royal family and experience royal treatment for yourself. Get in touch with us today for a free quote.">
    <meta property="og:image" content="{% static 'RoyalSite/images/royal_logo.jpg' %}">
    <meta name="viewport" content="width=device-width, intial-scale=1.0">
    
    <link rel="stylesheet" type="text/css" href="{% static 'RoyalSite/css/base.css' %}"> 
    <link rel="shortcut icon" href="{% static 'RoyalSite/images/royal_logo.jpg' %}">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-472RGL8TYW"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-472RGL8TYW');
    </script>
    {% if home %}
      <link rel="stylesheet" type="text/css" href="{% static 'RoyalSite/css/home.css' %}">
    {% elif posts %}
      <link rel="stylesheet" type="text/css" href="{% static 'RoyalSite/css/posts.css' %}">
    {% elif abouts %}
      <link rel="stylesheet" type="text/css" href="{% static 'RoyalSite/css/about.css' %}">
    {% elif gallery %}
      <link rel="stylesheet" type="text/css" href="{% static 'RoyalSite/css/gallery.css' %}">
    {% elif post %}
      <link rel='stylesheet' type="text/css" href="{% static 'RoyalSite/css/post.css' %}">
    {% endif %}
  </head>
  <body>
    <div id="wrapper">
      <nav class="navbar">
        <a href="{% url 'RoyalPages:home' %}"><img id="logo" src="{% static 'RoyalSite/images/Ico2.jpeg' %}"></a>
        <ion-icon name="menu-outline" class="toggle"></ion-icon>
        <ul class = "desktop show">
          <!-- Add close button, Make toggle disapear after openning menu -->
          <li><a class="home" href="{% url 'RoyalPages:home' %}">Home</a></li>
          <li><a class="posts" href="{% url 'RoyalPages:posts' %}">Blog Posts</a></li>
          <li><a class="about" href="{% url 'RoyalPages:about' %}">About Us</a></li>
          <li><a class="Gallery" href="{% url 'RoyalPages:gallery' %}">Gallery</a></li>
        </ul>
      </nav>
      {% block intro %}
      {% endblock intro %}
    </div>
    {% block body %}
    {% endblock body %}
    <script>
      document.addEventListener("DOMContentLoaded", function(){
        const mobile = document.querySelector(".show");
        const bars = document.querySelector(".toggle");
        const logo = document.querySelector("#logo");
        var view  = true

        var viewport = document.querySelector("meta[name=viewport]");
        viewport.setAttribute('content', viewport.content + ", height=" + window.innerHeight);
        console.log(window.innerWidth )
        function check_view() {
          if (window.innerWidth <= 600){
            logo.setAttribute("src").setAttribute("src", "{% static 'RoyalSite/images/Ico2.jpeg' %}");
          }
        }
        
        function openMenu(){
          mobile.classList.remove("desktop");
          mobile.classList.add("mobile");
        }

        function closeMenu(){
          mobile.classList.remove("mobile");
          mobile.classList.add("desktop");
        }

        bars.addEventListener("click", () => {
          if(mobile.classList.contains('mobile')){
            closeMenu();
          }else{
            openMenu();
          }
        });
        // X.addEventListener("click", closeMenu, false);

      });
      
    </script>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
  </body>
</html>

RoyalPages/templates/RoyalPages/gallery.html
{% extends 'RoyalPages/base.html' %}
{% load static %}

{% block intro %}
<section>
  <h1>Gallery</h1>
</section>
{% endblock intro %}
{% block body %}
  <div class="fullImage">
    <img class="fImg" src="/RoyalSite/images/RoyalSite/static/RoyalSite/images/gallery/WhatsApp_Image_2021-06-19_at_21.06.23_1.jpeg" placeholder="image not found">
    <span id='close' onclick="closeFullImg()">X</span>
    <div class="buttons">
      <div><ion-icon name="chevron-back-outline" onclick="prev()" ></ion-icon><p class="tooltip">previous</p></div>
      <div><ion-icon id='slide' name="caret-forward-circle-outline" onclick="slide()"></ion-icon><p id='slide-info' class="tooltip">slideshow</p></div>
      <div><ion-icon name="chevron-forward-outline" onclick="next()"></ion-icon><p class="tooltip">next</p></div>
    </div>
  </div>
  <div class="gallery" id='gala'>
    {% for image in gallery %}
    <div class="img">
      <!-- Check alt tag image.title.title to make sure it returns the images title -->
      <img id="{{image.pk}}" class="cImg" src='{{image.image.url}}' placeholder="image not found" onclick="openFullImg(this.src, this.id)" alt="{{image.title.title}}">
      {% if image.title %}
        <p class="tooltip">{{image.title.title}}</p>
      {% endif %}
    </div>
    {% empty %}
      <p>No Images have been posted to the gallery yet...</p>
    {% endfor %}
  </div>
  <script src="{% static 'RoyalSite/js/gallery.js' %}"></script>
{% endblock body %}

RoyalPages/templates/RoyalPages/home.html
{% extends 'RoyalPages/base.html' %}
{% load static %}

{% block intro %}
  <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
  <meta content="utf-8" http-equiv="encoding">
  <div class="content">
    <div class='fades'>
      <h1 id='italic'>Leave the dirty work to us!</h1>
      <p id="shows" ></p>
    </div>
    <button>
      <p><a href="tel:+233555506625">Contact Us</a></p>
    </button>
  </div>
  <p>control</p>
  <ul id='info'>

  </ul>
  
      <!-- <ion-icon name="call"></ion-icon> -->
  <script>
    var data = '{{abouts_qs}}'
    var rdata = JSON.parse(data.replace(/&quot;/ig, '"'))
    var num = 0;
    var fades = document.querySelector('.fades');
   
    var changetime = 13000

    document.addEventListener("DOMContentLoaded", function() {
      var boobs = setInterval(change, changetime);
    });

    
    function start_fade() {
      var Xinterval = setInterval(fade, 200);
      var text = rdata[num]['fields']['text']
      var italics = rdata[num]['fields']['title']
      var background = rdata[num]['fields']['background']
      var nubs = 0;

      function fade () {
        
        var opacity = getComputedStyle(fades).opacity
        
        nubs += 1; 
        console.log(opacity)
        fades.style.opacity = opacity - 1/15;
        if (nubs == 15) {
          clearInterval(Xinterval);
          document.querySelector('#italic').innerHTML = italics;
          document.querySelector('#shows').innerHTML = text
          document.getElementById('wrapper').style.backgroundImage = `url(/static/RoyalSite/css/${background})`

          wait()
        }
      };
    }
    
    function wait() {
      n = 0
      clear = setInterval(()=> {
        n += 1;
        if (n == 1){
          clearInterval(clear)
          start_pop();
        }
      }, 2000);
    }


    function start_pop() {
      var Cinterval = setInterval(pop, 200);

      var stubs = 0;

      function pop(){
        var opacity = getComputedStyle(fades).opacity;
        
        console.log(opacity);

        stubs += 1/25;
        fades.style.opacity = stubs;
        if (fades.style.opacity >= 1){
          clearInterval(Cinterval);
        }
      };
    };
    
    function change() {
    
      start_fade();
     
      if (num < rdata.length - 1) {
          num += 1
      } else {
          num = 0  
      }
      
    }; 

  </script>
  <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
{% endblock intro %}

RoyalPages/templates/RoyalPages/post.html
{% extends 'RoyalPages/base.html' %}
{% load static %}

{% block intro %}
    <section>
        <h1>Blog Post</h1>
    </section>
{% endblock intro %}


{% block body %}
<img id="background" src="{% static 'RoyalSite/images/glass.jpg' %}">

<div id="content">
  <div id="title">
    <h3>Topic: {{ post.title }} / by {{ post.owner}}</h3>
  </div>

  <div id="page">
    <p> {{ post.text|linebreaks }}</p>
    <button><a href="{% url 'RoyalPages:posts' %}">Return</a></button>
  </div>
  <p id="comments">Comments</p>
  <div id="cusdis_thread"
  data-host="https://cusdis.com"
  data-app-id="ee76089d-c370-4c7c-82d4-65e2d9e0ae7e"
  data-page-id="{{ post.pk }}"
  data-page-url="{% url 'RoyalPages:blog' post.pk %}"
  data-page-title="{{ post.title }}"></div>

</div>

<script async defer src="https://cusdis.com/js/cusdis.es.js">
  const background = document.getElementById("background");
  
</script>
{% endblock body %}

RoyalPages/templates/RoyalPages/posts.html
{% extends 'RoyalPages/base.html' %}
{% load static %}

{% block intro %}
  <section>
    <h1>Blog Posts</h1>
  </section>
{% endblock intro %}

{% block body %}
  <div class="main">
    <div class="post-list">
      <h2>Recent Posts</h2>
      <hr/>
      <ul>
        {% for post in posts %}
          <div class="post">
            <div class="post-info">
              <a href="{% url 'RoyalPages:blog' post.pk %}">{{ post.title }}</a>&middot;
              <p> by {{ post.owner }} | {{ post.date_added|date:'M d, Y H:i' }}.</p>
            </div>
            <div class="post-text">
            <p>{{ post.text|linebreaks }}</p>
            <div class="buttons">
              <div class="views">Views: {{post.views}}</div>
              <button><a href="{% url 'RoyalPages:blog' post.pk %}">Read</a></button>
            </div>
          </div>
        {% endfor %}
      </ul>
    </div>
    <div class="search-sec">
      <form id="search-form" autocomplete="off">
        {% csrf_token %}
        <input type="text" id="search-input" class="search" placeholder="Search Posts">
      </form>
      <div id='search-items'>
        <p id='list-title'>Popular Posts</p>
        <ul id="list">
        {% for item in popular %}
          <li><a href="{% url 'RoyalPages:blog' item.pk %}">{{ item.title }}</a><br /> <i class="list-item">{{ item.text }}</i></li>
        {% empty %}
          No posts...
        {% endfor %}      
        </ul>
        </div>
    </div>
  </div>
  <script>
  const ata = '{{ popular_qs }}'
  console.log(ata)
  </script>
  <script src="{% static 'RoyalSite/js/jquery.js' %}"></script>
  <script src="{% static 'RoyalSite/js/posts.js' %}"></script>
{% endblock body %}